project_name: copy-deployment
version: '2'
builds:
  - os: [linux, darwin, windows]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./go-project/copy-deployment.go