name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Grant write permissions to the workflow

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build for Linux
        run: |
          cd ./go-project
          GOOS=linux GOARCH=amd64 go build -o copy-deployment-linux-amd64 copy-deployment.go

      - name: Build for Windows
        run: |
          cd ./go-project
          GOOS=windows GOARCH=amd64 go build -o copy-deployment-windows-amd64.exe copy-deployment.go

      - name: Build for macOS
        run: |
          cd ./go-project
          GOOS=darwin GOARCH=amd64 go build -o copy-deployment-darwin-amd64 copy-deployment.go

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./go-project/copy-deployment-linux-amd64
            ./go-project/copy-deployment-windows-amd64.exe
            ./go-project/copy-deployment-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
